//! Regenerates `tests/test-vectors.json`:
//!
//! ```sh
//! cargo run -p teton-proto --example gen_vectors > tests/test-vectors.json
//! ```
//!
//! Inputs are fixed; outputs come from the Rust implementation. The JS
//! configurator must reproduce every output byte for byte.

use aws_lc_rs::digest::{SHA256, digest};
use serde_json::{Value, json};
use teton_proto::crypto::{Channel, KeyPair, derive_session_keys, hkdf_info};
use teton_proto::frame::chunk;
use teton_proto::label::{Label, device_id};
use teton_proto::msg::*;
use teton_proto::{hex, msg};

const BASE_URL: &str = "https://royster57.github.io/teton-provision/";

fn scalar(label: &str) -> Vec<u8> {
    digest(
        &SHA256,
        format!("teton-provision test vector: {label}").as_bytes(),
    )
    .as_ref()
    .to_vec()
}

fn main() {
    let device = KeyPair::from_scalar(&scalar("device")).unwrap();
    let eph = KeyPair::from_scalar(&scalar("ephemeral")).unwrap();
    let id = device_id(device.public_key());
    let nonce: Vec<u8> = (0u8..16).collect();

    let z = eph.agree(device.public_key()).unwrap();
    let keys =
        derive_session_keys(&*z, &nonce, &id, eph.public_key(), device.public_key()).unwrap();
    let mut phone = Channel::initiate(&eph, device.public_key(), &id, &nonce).unwrap();
    let mut dev = Channel::accept(&device, &id, &nonce, eph.public_key()).unwrap();

    let phone_msgs = [
        msg::encode(&PhoneMsg::Open),
        msg::encode(&PhoneMsg::Scan),
        msg::encode(&PhoneMsg::Join(JoinRequest {
            ssid: "roy".into(),
            psk: Some(Secret::new("correct horse".into())),
            sec: None,
            hidden: false,
        })),
        msg::encode(&PhoneMsg::Ack),
    ];
    let device_msgs = [
        msg::encode(&DeviceMsg::Ready {
            state: DeviceState::Unprovisioned,
            retry_after: 0,
            version: "0.1.0".into(),
        }),
        msg::encode(&DeviceMsg::Networks {
            list: vec![
                Network {
                    ssid: "roy".into(),
                    signal: 82,
                    sec: Security::Wpa2Wpa3,
                },
                Network {
                    ssid: "Café Guest".into(),
                    signal: 40,
                    sec: Security::Open,
                },
            ],
        }),
        msg::encode(&DeviceMsg::Status(Status::stage(Stage::Accepted))),
        msg::encode(&DeviceMsg::Status(Status {
            ip: Some("192.168.1.42".into()),
            internet: Some(Internet::Full),
            ..Status::stage(Stage::Done)
        })),
    ];
    let seal_all = |ch: &mut Channel, msgs: &[Vec<u8>]| -> Vec<Value> {
        msgs.iter()
            .map(|m| {
                json!({
                    "plaintext": String::from_utf8(m.clone()).unwrap(),
                    "ciphertext": hex(&ch.seal(m).unwrap()),
                })
            })
            .collect()
    };
    let p2d = seal_all(&mut phone, &phone_msgs);
    let d2p = seal_all(&mut dev, &device_msgs);

    let label = Label::new(device.public_key());
    let url = label.url(BASE_URL);
    let other = KeyPair::from_scalar(&scalar("other")).unwrap();

    let long_msg = "x".repeat(900);
    let framing: Vec<Value> = [(20usize, r#"{"t":"hello","v":1}"#), (8, &long_msg)]
        .iter()
        .map(|(max, m)| {
            json!({
                "max_chunk_len": max,
                "message": m,
                "chunks": chunk(m.as_bytes(), *max).unwrap().iter().map(|c| hex(c)).collect::<Vec<_>>(),
            })
        })
        .collect();

    let vectors = json!({
        "description": "Cross-implementation vectors for teton-provision protocol v1 (SPEC.md §3–§5). Byte fields are lowercase hex. Generated by `cargo run -p teton-proto --example gen_vectors`.",
        "session": {
            "device_private": hex(&device.scalar().unwrap()),
            "device_public": hex(device.public_key()),
            "device_id": id,
            "ephemeral_private": hex(&eph.scalar().unwrap()),
            "ephemeral_public": hex(eph.public_key()),
            "nonce": hex(&nonce),
            "shared_secret": hex(&*z),
            "hkdf_info": hex(&hkdf_info(&id, eph.public_key(), device.public_key())),
            "k_pd": hex(&*keys.phone_to_device),
            "k_dp": hex(&*keys.device_to_phone),
            "phone_to_device": p2d,
            "device_to_phone": d2p,
        },
        "label": {
            "base_url": BASE_URL,
            "url": url,
            "display_id": teton_proto::label::format_id(&label.id),
        },
        "invalid_labels": [
            { "url": BASE_URL, "error": "missing_fragment" },
            { "url": url.replace("v=1", "v=2"), "error": "unsupported_version" },
            { "url": url.replace("&pk=", "&pq="), "error": "missing_param" },
            { "url": url.replace(&label.id, &device_id(other.public_key())), "error": "id_mismatch" },
            { "url": format!("{url}AA"), "error": "bad_public_key" },
        ],
        "framing": framing,
    });
    println!("{}", serde_json::to_string_pretty(&vectors).unwrap());
}
